### ISSUE TITLE
Suggestion for the throw hitboxes

### ISSUE THREAD

**Issue by Athenya** [kkots/ggxrd_hitbox_overlay_2211#1]
Would it be possible to add a mode where the hitboxes on throws are shown in their pure form, that doesn't get stretched by the opponent's pushbox, so that nyo'll have a more accurate way to represent them on things like Dustloop?

**Comment by kkots** [comment]
I'll get on it. I will add setting to the .ini file that makes throw boxes
that check pushbox proximity specifically display without getting affected
by the opponent's pushbox width. That would mean that such throw box
connects when it touches the opponent's pushbox.

**Comment by Athenya** [comment]
Thanks a lot!
![billede](https://github.com/kkots/ggxrd_hitbox_overlay_2211/assets/68659172/1192651e-7472-4cf7-ad93-a3a893170f5e)
